name: Codecept
on:
  push:
    branches:
      - master
jobs:
  Ubuntu:
    strategy:
      fail-fast: false
    timeout-minutes: 10
    name: Run Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1
      
      - name: run CodeceptJS tests
        run: npx codeceptjs run
