name: Codecept
on:
  push:
    branches:
      - master
jobs:
  Ubuntu:
    strategy:
      fail-fast: false
    timeout-minutes: 10
    name: Run Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: microsoft/playwright-github-action@v1

      - name: run CodeceptJS tests
        run: npm install && npm run codeceptjs:headless
